/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '17/09/15 10:13 PM' with Gradle 2.7
 *
 * @author MarkPerry, @date 17/09/15 10:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
